version: "3"
services:
  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - ~/data/redis:/data
    command: redis-server
    ports:
      - '127.0.0.1:6379:6379'
